### PR TITLE
Additional Feature: A navigation bar for landing page

### PR DESCRIPTION
**Pull request by rudrathegreat**
The reason why I added the navigation bar was related to issue #14 in which I said that to make the user experience better on the page and to make it easier for the user to get to different parts of the website more easily, a navbar is the best option. The changes I have made are - 

- Develop the navbar in html
- Developed the CSS code for the navbar
- Made the navbar change in size depending on the viewport width
- Made the text change in size depending on window size (easier for people to read on mobile devices)
- Made the navbar responsive on mobile devices

Please let me know your thought ASAP.

### CODE REVIEW

**Comment by Hexsphere** [comment]
I really wanna clarify that the landing isn't our focus... I mean nothing against you working on it but still lol

**Comment by rudrathegreat** [comment]
I understand that, but I feel that if we are going to be working on the app, we need to make sure that people know what we are doing.

**Comment by Hexsphere** [comment]
agreed 👍

**Comment by rudrathegreat** [comment]
cool!

**Pull request merged**
