### PR TITLE
Fixed issue with the down button

### PR DESCRIPTION
**Pull request by BonfireScratch**
In your code, the down button did not work when clicked. This has now been fixed by adding an `id` tag in the About container.

### CODE REVIEW

**Comment by BonfireScratch** [comment]
@micahlt @ConvexPolygon

**Comment by ConvexPolygon** [comment]
Yep, It's good!

**Comment by YOYITsM3M8** [comment]
its wrong color!!!!
its black and you can barely see it

**Comment by BonfireScratch** [comment]
@YOYITsM3M8 I did not change the styling and I am fairly sure that it was the case before the PR was opened

**Comment by YOYITsM3M8** [comment]
Oh ok, someone should still fix it.

**Comment by micahlt** [comment]
@YOYITsM3M8 I'll work on it.  I'm building out a major update with some stuff @locness3 requested on issue #6.

**Comment by YOYITsM3M8** [comment]
Ok

**Pull request merged**
