### PR TITLE
Make the website responsive

### PR DESCRIPTION
**Pull request by BonfireScratch**
This PR makes the website responsive

### CODE REVIEW

**Comment by micahlt** [comment]
@BonfireScratch more work will need to be done on the SCSS side of things, but thanks!  Merged.

**Comment by BonfireScratch** [comment]
@micahlt are you going to use Sass as well as plain CSS?

**Comment by micahlt** [comment]
Ah, snap, sorry, I thought that this issue was in the client repo, not the landing.  Nope, there's no need for Sass on the landing page.

**Comment by BonfireScratch** [comment]
@micahlt ah, OK

**Pull request merged**
