### PR TITLE
New Section: Latest News Section

### PR DESCRIPTION
**Pull request by rudrathegreat**
Okay, I was reading some news on this website, and I was thinking, why don't we put our latest news regarding the mobile app on our website. This is where the Latest News Section comes in! Here's the new features I've added - 

- New Section by the name of Latest News
- Users can add a title, a one line description and a link to the latest news
- Made this section responsive on mobile devices
- Increased Responsiveness of previous sections including tagline section, etc.
- Improving website design to make text easy to read, esp. on small screens
- Added new option in navbar, 'news'
- and much more!

Please let me know your feedback, I think there should be a 'Meet the team section' and then this section comes in. I was also thinking that we could have a slider here, but then that would be hard to maintain.

### CODE REVIEW

**Comment by rudrathegreat** [comment]
i think it's ready to merge, don't you think?

**Comment by rudrathegreat** [comment]
@micahlt what do u think? should we merge this?

**Comment by micahlt** [comment]
@rudrathegreat Looks great!  I'll merge, but first I'd like to make the navbar a little smaller.

**Comment by BonfireScratch** [comment]
@micahlt yeah, the bottom margin of the navbar is way too big and it makes it look assymetric

**Comment by micahlt** [comment]
@BonfireScratch Yeah.  I fixed most of it, but the padding should probably be less dynamic.  Merging this to the `develop` branch.

**Comment by BonfireScratch** [comment]
@micahlt Isn't this ready for `master`?

**Comment by micahlt** [comment]
@BonfireScratch Nope, it's still lorem ipsum right now- it needs to have content to be in master.

**Comment by rudrathegreat** [comment]
I was thinking you guys could fill in some news regarding the app like New Feature! i dunno

**Comment by rudrathegreat** [comment]
btw with the changes made to the navbar, i liked all of it, makes more sense, much more responsive thanks @micahlt

**Pull request merged**
