### PR TITLE
Add New Section (In Development)

### PR DESCRIPTION
**Pull request by ConvexPolygon**
Add an Our Team section.

### CODE REVIEW

**Comment by ConvexPolygon** [comment]
(Still working on CSS)

**Comment by micahlt** [comment]
Cool, let me know when this is done.  I'll need to test it, of course.

**Comment by micahlt** [comment]
@ConvexPolygon once again, let me know when this is ready to merge.

**Comment by micahlt** [comment]
@ConvexPolygon What's the status on this?

**Comment by ConvexPolygon** [comment]
Oof I forgot about it.

**Comment by rudrathegreat** [comment]
An Our Team section sounds like a really good idea!

**Comment by ConvexPolygon** [comment]
Like it!

**Comment by rudrathegreat** [comment]
I was also thinking of doing like a Latest News Section in which we mention the latest updates to the mobile app. I'll work on that section.

**Comment by BonfireScratch** [comment]
Neat idea!

**Comment by rudrathegreat** [comment]
@BonfireScratch I have implemented the idea with 'Lorem Ipsum' placeholders and I am creating an new branch for this new section, u can check out the code there

**Comment by rudrathegreat** [comment]
I think another thing to consider is a footer, who's going to do that?

**Comment by micahlt** [comment]
@ConvexPolygon Status?

**Comment by rudrathegreat** [comment]
Guys check out my recent pull request, currently merge it into the develop branch, then tell everyone to put their info in the placeholders.

**Pull request closed without merging**
